name: Jekyll Post Creator

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Fetch READMEs and create posts
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        curl -s https://api.github.com/users/TheManWhoLikesToCode/repos?per_page=100 | jq -r '.[].name' | while read repo; do
          readme=$(curl -s https://raw.githubusercontent.com/TheManWhoLikesToCode/$repo/master/README.md)
          if [ "$readme" != "404: Not Found" ]; then
            echo -e "---\nlayout: post\ntitle:  \"$repo\"\ndate:   $(date +"%Y-%m-%d")\ncategories: jekyll update\n---\n$readme" > ./_posts/$(date +"%Y-%m-%d")-$repo.md
            git add .
            git commit -m "Add new post: $repo"
            git push
          fi
        done
