name: Jekyll Post Creator

on:
  schedule:
    - cron: "0 0 * * *" # This schedules the action to run at midnight every day
  workflow_dispatch: # This allows you to manually trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_PAT }} # Make sure to set this secret in your GitHub repo settings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Create _posts directory
        run: mkdir -p _posts

      - name: Fetch READMEs and create posts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          ruby scripts/create_posts_from_repos.rb

      - name: Commit files
        run: |
          git add .
          git commit -m "Add posts"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
