name: Update Portfolio

on: 
  push:
    branches:
      - main  # Trigger the workflow on push or pull request to the main branch

jobs:
  update_portfolio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Fetch and create posts
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        # This script will use GitHub API to fetch your repos and create posts
        # You need to create this script, see the next step
        ruby ./scripts/create_posts_from_repos.rb

    - name: Build site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./_site
