name: Jekyll Post Creator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Create _posts directory
      run: mkdir -p _posts

    - name: Fetch READMEs and create posts
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        ruby scripts/create_posts_from_repos.rb
