name: Jekyll Post Creator

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Fetch READMEs and create posts
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        require 'net/http'
        require 'json'
        require 'date'
        require 'base64'

        GITHUB_USERNAME = 'TheManWhoLikesToCode'
        GITHUB_API_URL = "https://api.github.com/users/#{GITHUB_USERNAME}/repos"

        # Fetch repositories from GitHub
        uri = URI(GITHUB_API_URL)
        response = Net::HTTP.get(uri)
        repositories = JSON.parse(response)

        # Loop through repositories and create posts
        repositories.each do |repo|
          title = repo['name']
          description = repo['description']
          url = repo['html_url']

          # Extract the creation date and format it
          creation_date = DateTime.parse(repo['created_at']).strftime("%Y-%m-%d")

          # Fetch README
          readme_uri = URI("https://api.github.com/repos/#{GITHUB_USERNAME}/#{title}/readme")
          readme_response = Net::HTTP.get(readme_uri)
          readme = JSON.parse(readme_response) rescue nil

          # Decode README content from base64
          readme_content = readme && readme['content'] ? Base64.decode64(readme['content']) : "No README available for this repository."

          # Create the post file
          File.open("./_posts/#{creation_date}-#{title}.markdown", "w") do |file|
            file.puts("---")
            file.puts("layout: post")
            file.puts("title: #{title}")
            file.puts("description: #{description}")
            file.puts("---")
            file.puts(readme_content)
            file.puts("[Go to repository](#{url})")
          end

          git add .
          git commit -m "Add new post: #{title}"
          git push
        end
